<?php

namespace AppBundle\Repository;

/**
 * CommercialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommercialsRepository extends \Doctrine\ORM\EntityRepository
{
}
