<?php

namespace AppBundle\Repository;

/**
 * ConsultantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultantsRepository extends \Doctrine\ORM\EntityRepository
{
}
