<?php

namespace AppBundle\Repository;

/**
 * KeySucessFactorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeySucessFactorsRepository extends \Doctrine\ORM\EntityRepository
{
}
