<?php

namespace AppBundle\Repository;

/**
 * RequirementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequirementsRepository extends \Doctrine\ORM\EntityRepository
{
}
