app:
    resource: '@AppBundle/Controller/'
    type: annotation

apiuser:
    type:     rest
    resource: AppBundle\Controller\ApiUserController

auth-tokens:
    type:     rest
    resource: AppBundle\Controller\UserKeyController

commercials:
    type:     rest
    resource: AppBundle\Controller\CommercialsController

requirements:
    type:     rest
    resource: AppBundle\Controller\RequirementsController

customers:
    type:     rest
    resource: AppBundle\Controller\CustomersController

status:
    type:     rest
    resource: AppBundle\Controller\StatusController

