<?php
/**
 * Created by PhpStorm.
 * User: Niquelesstup
 * Date: 05/10/2017
 * Time: 00:42
 */

namespace SnapAtSdk;


use SnapAtSdk\ClassesMetiers\ClasseMetierInterface;
use SnapAtSdk\ClassesMetiers\Consultants;
use SnapAtSdk\ClassesMetiers\Customers;

class CustomersAction extends Actions
{

    public function __construct($url, $api_key, $modeProduction)
    {
        parent::__construct($url, $api_key, $modeProduction);
        $this->objet = new Customers();
    }

    public function GetAll()
    {
        return parent::GetAll(); // TODO: Change the autogenerated stub
    }


}