<?php
/**
 * Created by PhpStorm.
 * User: Niquelesstup
 * Date: 05/10/2017
 * Time: 00:42
 */

namespace SnapAtSdk;


use SnapAtSdk\ClassesMetiers\Requirements;

class RequirementsAction extends Actions
{

    public function __construct($url, $api_key, $modeProduction)
    {
        parent::__construct($url, $api_key, $modeProduction);
        $this->objet = new Requirements();
    }

    public function GetAll()
    {
        return parent::GetAll(); // TODO: Change the autogenerated stub
    }

    public function Supprimer($id)
    {
        return parent::Supprimer($id); // TODO: Change the autogenerated stub
    }

}